---
# vars file for add-job-to-bareos-director


#####     Required Variables      #####
# Fill in appropriate values below unless passing from a higher precedence

# Имя хоста машины, для которой вы создаете резервную копию
add_job_to_bareos_director_host_name: "msk-fileserver"

# Полное доменное имя или IP-адрес компьютера, который вы добавляете для резервного копирования
add_job_to_bareos_director_server_fqdn: "172.0.0.107"

# Полное доменное имя или IP-адрес, где работает демон / служба Bareos Storage.
add_bareos_storage_daemon_fqdn: "backup-disk3"

# Пароль должен соответствовать введенному клиентскому паролю при добавлении клиентской программы bareos на компьютер, который вы хотите сделать резервную копию. Значение для этого обычно является очень длинной строкой (47 символов) случайных символов.
add_job_to_bareos_director_client_password: "FS/tNxEM3FYzH299frpGaNgWYCAeYz2tb3nOqyhSPqgl"

# The storage director password variable is the bareos-dir password found on your Bareos Server
#add_job_to_bareos_director_storage_director_password: "{{ lookup('env', 'BAREOS_STORAGE_PASSWORD') }}"


# Уровень резервного копирования - Full, Incremental, Differential
# Incremental - all ﬁles changed since the last Full, Diﬀerential, or Incremental backup started
# Diﬀerential - all ﬁles speciﬁed in the FileSet that have changed since the last successful *Full* backup will be backed up
# Full - all ﬁles in the FileSet whether or not they have changed will be backed up
add_job_to_bareos_director_level: Full

#Позволяет вам контролировать порядок выполнения ваших заданий. Чем выше число, тем ниже приоритет работы.
add_job_to_bareos_director_priority: 10

# Время которое будет выполнятся Backup 
add_job_to_bareos_director_backup_schedule:
  - Run = Full sun at 02:00
  - Run = Incremental mon-sat at 02:00

add_job_to_bareos_director_archive_device: "/z-storage/backups/{{ add_job_to_bareos_director_host_name }}"
# Файлы которые будут бекапится
add_job_to_bareos_director_filesets_to_backup:
  - File = "/var/www/html"
  - File = "/backups/mysql/current"
# Файлы которые будут исключены из бекапа
add_job_to_bareos_director_filesets_to_exclude:
  - File = "/var/www/html/.github"
  - File = "/var/www/html/.git"
  - File = "/var/www/html/.gitignore"
