path_persistent_iptables_rules: /etc/iptables/iptables.rules
os_family_specific_pre:
  # Needed for ansible module apt: upgrade
  - aptitude
  # Make firewall rules persistent across reboots
  - iptables-persistent
  # Make sure https repos can be added (needed for OpenVPN repo)
  - ca-certificates
path_dict: /usr/share/dict/american-english-huge
