---
#  - name: Update
#    apt: 
#     update_cache: yes
  
  - name: Upgrade
    apt: 
     upgrade: dist
  
  - name: Устанавливаем требуемые пакеты
    apt:
      name: "{{ packages }}"
      state: "present"
    with_items: "{{ packages }}"
#    when: ansible_os_family == "Debian" and ansible_distribution == "Ubuntu"
