---
<<<<<<< HEAD
  - name: Update
    apt:
     update_cache: yes
=======
#  - name: Update
#    apt: 
#     update_cache: yes
>>>>>>> bb321bc4edd2283f22b3c270248dd01c7db469b5
  
  - name: Upgrade
    apt: 
     upgrade: dist
  
  - name: Устанавливаем требуемые пакеты
    apt:
      name: "{{ item }}"
      state: "present"
    with_items: "{{ packages }}"
    when: ansible_os_family == "Debian"
