---
#   - name: "Add the official OpenVPN APT key; hiding 25 lines of log..."
#     apt_key:
#      id: E158C569
#      data: "{{ item }}"
#     with_file: openvpn_signing.key
#     no_log: True
   - name: OpenVPN | package | Get official OpenVPN APT key
  # Work around for ansible issue https://github.com/ansible/ansible/issues/22647
     get_url:
      url: https://swupdate.openvpn.net/repos/repo-public.gpg
      dest: ~/openvpn.gpg
     when: ansible_os_family == "Debian"
   

   - name: OpenVPN | package | Add the official OpenVPN APT key
 #  Work around for ansible issue https://github.com/ansible/ansible/issues/22647
     apt_key:
      file: ~/openvpn.gpg
      state: present
     when: ansible_os_family == "Debian"

   - name: OpenVPN | package | Add the official OpenVPN repository
     apt_repository:
      repo: 'deb https://build.openvpn.net/debian/openvpn/stable {{ ansible_lsb.codename }} main'
      state: present
      update_cache: yes
     when: ansible_os_family == "Debian"

   - name: Устанавливаем требуемые пакеты
     apt:
      name: 
       - openvpn
       - git
       - iptables
       - dnsmasq
       - wamerican-huge
       - python-pip
       - python-virtualenv
       - python-pexpect
      state: 'present'

#   - name: OpenVPN | package | apt - upgrade any out of date packages
#     apt:
#       upgrade: safe
#     when: ansible_os_family == "Debian"
